apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: w163l3rf7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w163l3rf7-nodejs 
  name: w163l3rf7-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: w163l3rf7-nodejs
    weight: 100 
