apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w163l3rf7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w163l3rf7-nodejs 
  name: w163l3rf7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: w163l3rf7-nodejs 
